/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.model.Pet;
import org.example.repository.PetRepository;

import javax.swing.*;

/**
 *
 * @author xyz6269
 */
public class AddPetForum extends javax.swing.JPanel {

    /**
     * Creates new form AddPetForum
     */
    public AddPetForum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField24 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        petRepository = new PetRepository();

        setBackground(new java.awt.Color(45, 50, 55));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField24.setBackground(new java.awt.Color(45, 50, 55));
        jTextField24.setText("pet picture");
        jTextField24.setBorder(null);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 222, 40));

        jButton1.setBackground(new java.awt.Color(173, 216, 230));
        jButton1.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(22, 25, 28));
        jButton1.setText("add png");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 110, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 250, 20));

        jTextField25.setBackground(new java.awt.Color(45, 50, 55));
        jTextField25.setText("pet name");
        jTextField25.setBorder(null);
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 222, 40));

        jTextField26.setBackground(new java.awt.Color(45, 50, 55));
        jTextField26.setText("pet type");
        jTextField26.setBorder(null);
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 222, 40));

        jTextField27.setBackground(new java.awt.Color(45, 50, 55));
        jTextField27.setText("pet age");
        jTextField27.setBorder(null);
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 222, 40));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 250, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 250, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 250, 20));

        jButton2.setBackground(new java.awt.Color(173, 216, 230));
        jButton2.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(22, 25, 28));
        jButton2.setText("add pet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.showOpenDialog(this);
        jTextField24.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pet pet = new Pet();
        pet.setName(jTextField25.getText());
        pet.setAge(Integer.parseInt(jTextField27.getText()));
        pet.setType(jTextField26.getText());
        pet.setPicture(jTextField24.getText());
        petRepository.create(pet);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private PetRepository petRepository;
    // End of variables declaration//GEN-END:variables
}
