package org.example.view;

import org.example.model.Request;
import org.example.repository.PetRepository;
import org.example.repository.RequestRepository;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;

public class RequestsPage extends javax.swing.JPanel {

    /**
     * Creates new form RequestPage
     */
    public RequestsPage() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(45, 50, 55));
        setMaximumSize(new java.awt.Dimension(879, 698));
        setMinimumSize(new java.awt.Dimension(879, 698));
        setPreferredSize(new java.awt.Dimension(879, 698));
        setBackground(new java.awt.Color(45, 50, 55));
        setForeground(new java.awt.Color(45, 50, 55));
        setLayout(new java.awt.GridLayout(0, 3, 12, 10));
        for (Request request : requestRepository.findAll()) {
            RequestItem item = mapToItem(request);
            add(item);
        }
    }// </editor-fold>//GEN-END:initComponents

    private RequestItem mapToItem(Request request) {
        RequestItem item = new RequestItem();
        ImageIcon icon = new ImageIcon(getClass().getResource(request.getPetToAdopt().getPicture()));
        Image scaledImage = icon.getImage().getScaledInstance(270, 146, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        item.getjLabel8().setText(request.getEmail());
        item.getjLabel9().setText(request.getJob());
        item.getjLabel10().setText(request.getPetToAdopt().getName());
        item.setPetid(request.getId());
        item.getjLabel1().setIcon(scaledIcon);

        return item;
    }

    private RequestRepository requestRepository = new RequestRepository();
    private PetRepository PetRepository = new PetRepository();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
