/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.model.Request;
import org.example.repository.PetRepository;
import org.example.repository.RequestRepository;

import javax.swing.*;

/**
 *
 * @author xyz6269
 */
public class RequestItem extends javax.swing.JPanel {

    /**
     * Creates new form RequestItem
     */
    public RequestItem() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        petRepository = new PetRepository();
        requestRepository = new RequestRepository();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(22, 25, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(22, 25, 28));
        jLabel8.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(173, 216, 230));
        jLabel8.setText("client-email:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, -1));

        jLabel9.setBackground(new java.awt.Color(22, 25, 28));
        jLabel9.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(173, 216, 230));
        jLabel9.setText("job-position:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, -1));

        jLabel10.setBackground(new java.awt.Color(22, 25, 28));
        jLabel10.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(173, 216, 230));
        jLabel10.setText("pet's name:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, -1, -1));

        jLabel11.setBackground(new java.awt.Color(22, 25, 28));
        jLabel11.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 123, 21));

        jLabel12.setBackground(new java.awt.Color(22, 25, 28));
        jLabel12.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 128, 170, 21));

        jLabel13.setBackground(new java.awt.Color(22, 25, 28));
        jLabel13.setFont(new java.awt.Font("JetBrainsMono NF", 1, 15)); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 77, 140, 21));

        jButton4.setBackground(new java.awt.Color(22, 25, 28));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request request = requestRepository.find(getPetid());
                request.setPetToAdopt(null);
                requestRepository.delete(request);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 40, 30));


        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 40, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 270, 190));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 140));
    }// </editor-fold>//GEN-END:initComponents


    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public int getPetid() {
        return petid;
    }

    public void setPetid(int petid) {
        this.petid = petid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private PetRepository petRepository;
    private RequestRepository requestRepository;
    private int petid;
    // End of variables declaration//GEN-END:variables
}
